package com.flatcode.littlebooksadmin.Unit;

import com.flatcode.littlebooksadmin.Activity.ADsActivity;
import com.flatcode.littlebooksadmin.Activity.AdsInfoActivity;
import com.flatcode.littlebooksadmin.Activity.AllBooksActivity;
import com.flatcode.littlebooksadmin.Activity.BookAddActivity;
import com.flatcode.littlebooksadmin.Activity.BookDetailsActivity;
import com.flatcode.littlebooksadmin.Activity.BookEditActivity;
import com.flatcode.littlebooksadmin.Activity.BookViewActivity;
import com.flatcode.littlebooksadmin.Activity.BooksCategoryActivity;
import com.flatcode.littlebooksadmin.Activity.CategoriesActivity;
import com.flatcode.littlebooksadmin.Activity.CategoryAddActivity;
import com.flatcode.littlebooksadmin.Activity.CategoryEditActivity;
import com.flatcode.littlebooksadmin.Activity.EditorsChoiceActivity;
import com.flatcode.littlebooksadmin.Activity.EditorsChoiceAddActivity;
import com.flatcode.littlebooksadmin.Activity.FavoritesActivity;
import com.flatcode.littlebooksadmin.Activity.FollowersActivity;
import com.flatcode.littlebooksadmin.Activity.FollowingActivity;
import com.flatcode.littlebooksadmin.Auth.ForgetPasswordActivity;
import com.flatcode.littlebooksadmin.Auth.LoginActivity;
import com.flatcode.littlebooksadmin.Activity.MainActivity;
import com.flatcode.littlebooksadmin.Activity.MyBooksActivity;
import com.flatcode.littlebooksadmin.Activity.PrivacyPolicyActivity;
import com.flatcode.littlebooksadmin.Activity.PrivacyPolicyEditActivity;
import com.flatcode.littlebooksadmin.Activity.ProfileActivity;
import com.flatcode.littlebooksadmin.Activity.ProfileEditActivity;
import com.flatcode.littlebooksadmin.Activity.ProfileInfoActivity;
import com.flatcode.littlebooksadmin.Activity.SliderShowActivity;
import com.flatcode.littlebooksadmin.Activity.SplashActivity;
import com.flatcode.littlebooksadmin.Activity.TopPublishersActivity;
import com.flatcode.littlebooksadmin.Activity.UsersActivity;

public class CLASS {
    public static Class MAIN = MainActivity.class;
    public static Class SPLASH = SplashActivity.class;
    public static Class LOGIN = LoginActivity.class;
    public static Class USERS = UsersActivity.class;
    public static Class CATEGORY_ADD = CategoryAddActivity.class;
    public static Class CATEGORY_EDIT = CategoryEditActivity.class;
    public static Class CATEGORY_BOOKS = BooksCategoryActivity.class;
    public static Class BOOK_ADD = BookAddActivity.class;
    public static Class BOOK_EDIT = BookEditActivity.class;
    public static Class BOOK_DETAIL = BookDetailsActivity.class;
    public static Class BOOK_VIEW = BookViewActivity.class;
    public static Class PROFILE = ProfileActivity.class;
    public static Class PROFILE_EDIT = ProfileEditActivity.class;
    public static Class PROFILE_INFO = ProfileInfoActivity.class;
    public static Class FOLLOWERS = FollowersActivity.class;
    public static Class FOLLOWING = FollowingActivity.class;
    public static Class MY_BOOKS = MyBooksActivity.class;
    public static Class FAVORITES = FavoritesActivity.class;
    public static Class PRIVACY_POLICY = PrivacyPolicyActivity.class;
    public static Class PRIVACY_POLICY_EDIT = PrivacyPolicyEditActivity.class;
    public static Class FORGET_PASSWORD = ForgetPasswordActivity.class;
    public static Class SLIDER_SHOW = SliderShowActivity.class;
    public static Class ALL_BOOKS = AllBooksActivity.class;
    public static Class ADS = ADsActivity.class;
    public static Class ADS_INFO = AdsInfoActivity.class;
    public static Class TOP_PUBLISHERS = TopPublishersActivity.class;
    public static Class EDITORS_CHOICE = EditorsChoiceActivity.class;
    public static Class EDITORS_CHOICE_ADD = EditorsChoiceAddActivity.class;
    public static Class CATEGORIES = CategoriesActivity.class;
}